name: Test

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=1g"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Check API Compatibility
        if: matrix.os == 'macos-latest'
        run: >
          ./gradlew apiCheck --stacktrace

      - name: Run macOS Tests
        if: matrix.os == 'macos-latest'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,IOS_ARM64,IOS_X64,IOS_SIMULATOR_ARM64,MACOS_ARM64,MACOS_X64,TVOS_ARM64,TVOS_X64,TVOS_SIMULATOR_ARM64,WATCHOS_ARM32,WATCHOS_ARM64,WATCHOS_DEVICE_ARM64,WATCHOS_X64,WATCHOS_SIMULATOR_ARM64,WASM_JS,WASM_WASI"

      - name: Run Linux Tests
        if: matrix.os == 'ubuntu-latest'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,ANDROID,ANDROID_ARM32,ANDROID_ARM64,ANDROID_X64,ANDROID_X86,LINUX_ARM64,LINUX_X64,WASM_JS,WASM_WASI"

      - name: Run Windows Tests
        if: matrix.os == 'windows-latest'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,MINGW_X64,WASM_JS,WASM_WASI"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report-${{ matrix.os }}-java${{ matrix.java-version }}
          path: '**/build/reports/tests/**'
          retention-days: 1
